/**
 * The color themes Codekin ships. A theme only changes colors — fonts, type
 * scale, radii and density are shared.
 *
 * Palettes live in CSS: Dark and Light in src/index.css, the rest in
 * src/themes/palettes.css (generated by scripts/generate-themes.mjs). The hex
 * values here are the few the app needs before or outside CSS (browser chrome
 * color, picker previews); registry.test.ts keeps them in step with the CSS.
 */

export const THEME_IDS = ['dark', 'light', 'midnight', 'paper', 'contrast', 'solarized', 'dracula', 'gruvbox', 'matrix'] as const

export type ThemeId = typeof THEME_IDS[number]

export type ThemeScheme = 'dark' | 'light'

export interface ThemeSwatches {
  /** neutral-12 — the page; also the browser `theme-color`. */
  page: string
  /** neutral-11 — sidebar and cards. */
  surface: string
  /** neutral-2 — primary text. */
  ink: string
  /** primary-5 */
  primary: string
  /** accent-5 */
  accent: string
}

export interface ThemeDefinition {
  id: ThemeId
  label: string
  scheme: ThemeScheme
  swatches: ThemeSwatches
}

export const THEMES: readonly ThemeDefinition[] = [
  { id: 'dark', label: 'Dark', scheme: 'dark', swatches: { page: '#0b0d0e', surface: '#161d1e', ink: '#cbd2d3', primary: '#e4ae42', accent: '#45b5c9' } },
  { id: 'light', label: 'Light', scheme: 'light', swatches: { page: '#fdfcfa', surface: '#f2efe8', ink: '#1b1a18', primary: '#b7884a', accent: '#248192' } },
  { id: 'midnight', label: 'Midnight', scheme: 'dark', swatches: { page: '#1b1f27', surface: '#222731', ink: '#d8dee9', primary: '#ebcb8b', accent: '#88c0d0' } },
  { id: 'paper', label: 'Paper', scheme: 'light', swatches: { page: '#f6f1e7', surface: '#efe8da', ink: '#2b2620', primary: '#8c6833', accent: '#3b6e7c' } },
  { id: 'contrast', label: 'High Contrast', scheme: 'dark', swatches: { page: '#000000', surface: '#0d0d0d', ink: '#f5f5f5', primary: '#ffd000', accent: '#4dd8ff' } },
  { id: 'solarized', label: 'Solarized Light', scheme: 'light', swatches: { page: '#fdf6e3', surface: '#eee8d5', ink: '#073642', primary: '#876d34', accent: '#2976b0' } },
  { id: 'dracula', label: 'Dracula', scheme: 'dark', swatches: { page: '#21222c', surface: '#282a36', ink: '#f8f8f2', primary: '#bd93f9', accent: '#8be9fd' } },
  { id: 'gruvbox', label: 'Gruvbox', scheme: 'dark', swatches: { page: '#1d2021', surface: '#282828', ink: '#ebdbb2', primary: '#fabd2f', accent: '#83a598' } },
  { id: 'matrix', label: 'Matrix', scheme: 'dark', swatches: { page: '#000000', surface: '#041208', ink: '#33ff66', primary: '#00ff41', accent: '#5cffc8' } },
]

export const DEFAULT_THEME: ThemeId = 'dark'

export function isThemeId(value: unknown): value is ThemeId {
  return typeof value === 'string' && (THEME_IDS as readonly string[]).includes(value)
}

export function getTheme(id: ThemeId): ThemeDefinition {
  return THEMES.find(t => t.id === id) ?? THEMES[0]
}

/**
 * Point the document at a theme: `data-theme` selects the palette,
 * `data-scheme` the polarity rules shared by every light or dark theme, and
 * the `theme-color` meta tints the browser chrome. index.html runs an inline
 * copy of this before first paint — keep the two in step.
 */
export function applyTheme(id: ThemeId): void {
  const theme = getTheme(id)
  const root = document.documentElement
  root.dataset.theme = theme.id
  root.dataset.scheme = theme.scheme
  document.querySelector('meta[name="theme-color"]')?.setAttribute('content', theme.swatches.page)
}
